/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kun_brother_header_checker_HeaderChecker */

#ifndef _Included_com_kun_brother_header_checker_HeaderChecker
#define _Included_com_kun_brother_header_checker_HeaderChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kun_brother_header_checker_HeaderChecker
 * Method:    checkNull
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kun_brother_header_checker_HeaderChecker_checkNull
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
